stages:
  - benchmark

include:
  - local: '/ci-scripts/docker_based_benchmark_job.yaml'

Trigger any benchmark:
  extends: .benchmark_api
  stage: benchmark

  rules:
    - when: manual

  variables:
    ## required
    ADDRESS: hive-staging.pl.syncad.com
    PORT: 58091

    ## optional
    ROOT_DIR: $CI_PROJECT_DIR

  tags:
    # - public-runner-docker
    - hivemind-heavy-job
    - hivemind-light-job
