stages:
  - benchmark

include:
  - local: '/ci-scripts/docker_based_benchmark_job.yaml'

Trigger any benchmark:
  extends: .benchmark_api
  stage: benchmark

  rules:
    - when: manual

  variables:
    ## required
    eADDRESS: hive-staging.pl.syncad.com
    ePORT: 58091

    ## optional
    eROOT_DIR: $CI_PROJECT_DIR

  tags:
    - tests-api
